# -*- coding: utf-8 -*-
"""pf. theory project 1.2.2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/116VY9JHE4bZgLwVFnXzSy7SJiS9P3CsE
"""

import random

def hangman():
    words = {
        "qualities_and_things": [
            "Jungle", "Book", "Cupboard", "Amazing", "person", "Countryside",
            "Personality", "superman", "Superstitious", "Regardless", "Memories",
            "Incredible", "Introvert", "extrovert", "Expectations",
            "Calendar", "Scenery", "Dining", "Cucumber", "Guava", "Anaconda",
            "Cabbage", "Microwave", "Gossip", "Repeating", "Laptop", "Switchboard",
            "Desktop", "Cousins", "Provide"
        ],
        "feelings ": [
            "Bravery", "Truthful", "Honesty", "Weakness", "Happiness", "Sadness",
            "Madness", "Responsibility", "Possibility", "probability", "ability",
            "Independent", "Free", "Silent"
        ],
        "subjects": [
            "program", "English", "urdu", "mathematics", "discrete", "science",
            "computer", "pakstudy", "physics"
        ],
        "names": [
            "Rizwan", "Khizar", "Wishma", "Humayun", "Uzma", "Alliyan", "Kainat",
            "Eshaal", "Mehwish", "Asifa"
        ]
    }

    category = random.choice(list(words.keys()))  # Randomly choose a category
    chosen_word = random.choice(words[category]).lower()  # Choose a word from the selected category
    display = ['_' if letter.isalpha() else letter for letter in chosen_word]  # Hide only alphabetic characters
    guessed_letters = []
    lives = 7
    game_over = False

    print(f"Hint: This word is related to {category.replace('_', ' ')}")  # Display the hint

    while not game_over:
        print(" ".join(display))
        guessed_letter = input("Guess a letter: ").lower()

        if guessed_letter in guessed_letters:
            print("You've already guessed that letter. Try again.")
            continue

        guessed_letters.append(guessed_letter)

        if guessed_letter not in chosen_word:
            lives -= 1
            print(f"Wrong guess! You have {lives} lives left.")
            if lives == 0:
                game_over = True
                print("You lose!! The word was:", chosen_word)
                break
        else:
            for position in range(len(chosen_word)):
                letter = chosen_word[position]
                if letter == guessed_letter:
                    display[position] = guessed_letter

        if '_' not in display:
            game_over = True
            print("Congratulations! You guessed the word:", chosen_word)
            break

        # Hangman display
        if lives == 7:
            pass
        elif lives == 6:
            print("  O  ")
        elif lives == 5:
            print("  O  ")
            print("  | ")
        elif lives == 4:
            print("  O  ")
            print(" /|  ")
        elif lives == 3:
            print("  O  ")
            print(" /|\ ")
            print("     ")
        elif lives == 2:
            print("  O  ")
            print(" /|\ ")
            print(" /   ")
        elif lives == 1:
            print("  O  ")
            print(" /|\ ")
            print(" / \  ")
            print("You lost! The word was:", chosen_word)
            break
hangman()
chosen_word = hangman()

if chosen_word:
    print(f"The last word was: {chosen_word}")

again = str(input("Do you want to play again, type yes or no: "))
if again.lower() == 'yes':
    chosen_word = hangman()
    if chosen_word:
        print(f"The last word was: {chosen_word}")

if again.lower() == 'no':
    print("Thank you")